# Generated by Django 3.2.9 on 2022-01-02 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project1', '0003_city_usersity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSity',
            new_name='UserCity',
        ),
        migrations.AddField(
            model_name='weather',
            name='city',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='project1.city'),
        ),
    ]
