# Generated by Django 3.2.9 on 2022-01-02 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0004_auto_20220102_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project1.city'),
        ),
    ]
