# Generated by Django 3.2.9 on 2022-01-02 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0005_alter_weather_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercity',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project1.city'),
        ),
    ]
