name: API Test

on:
  push:
    branches:
    - main

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          apiKey: PMAK-61c7434569eed9004764131c-f1109437f0cf89fd0b2238bef5acedec42
          collection: 18925000-37fc6ca4-9e3e-4680-83a0-e885ce3485cd
