name: Unfold deployed

on:
  workflow_run:
    workflows: ["SSH Deploy"]
    types:
      - completed
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: Deploy1
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.FOR_DEPLOY }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: touch /home/234.ha
