name: Unfold deployed


on:
  workflow_run:
    workflows: ["SSH Deploy"]
    types:
      - completed
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: Deploy1
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.FOR_DEPLOY_SERVER }}}
        username: ${{ secrets.FOR_DEPLOY_ROLE }}}
        password: ${{ secrets.FOR_DEPLOY }}}
        port: 22
        script: touch /home/234.ha
